#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2007-2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import argparse
from itertools import izip, chain, repeat, count

ap = argparse.ArgumentParser()
ap.add_argument('file1', metavar='FILE1', type=file)
ap.add_argument('file2', metavar='FILE2', type=file)
options = ap.parse_args()

f1 = options.file1
f2 = options.file2

for i, l1, l2 in izip(count(1), chain(f1, repeat(None)), chain(f2, repeat(None))):
    if l1 is None:
        if l2 is None:
            break
        else:
            print('{0}a{0}'.format(i))
    elif l2 is None:
        print('{0}d{0}'.format(i))
    else:
        if l1 == l2:
            continue
        print('{0}c{0}'.format(i))
    l1 is None or print('< {l}'.format(l=l1), end='')
    l2 is None or print('> {l}'.format(l=l2), end='')

# vim:ts=4 sts=4 sw=4 et
