#!/usr/bin/python
from itertools import izip, chain, repeat, count
from sys import argv, stdout, exit
write = stdout.write

if len(argv) != 3:
	write('Usage: %s <original> <new>' % argv[0])
	exit(1)

f1, f2 = map(file, argv[1:3])

for i, l1, l2 in izip(count(1), chain(f1, repeat(None)), chain(f2, repeat(None))):
	if l1 is None:
		if l2 is None:
			break
		else:
			write('%da%d\n' % (i, i))
	elif l2 is None:
		write('%dd%d\n' % (i, i))
	else:
		if l1 == l2:
			continue
		write('%dc%d\n' % (i, i))
	l1 is None or write('< %s' % l1)
	l2 is None or write('> %s' % l2)

# vim:ts=4 sw=4 noet
