#!/usr/bin/env python

import argparse
from itertools import izip, chain, repeat, count
from sys import stdout
write = stdout.write

ap = argparse.ArgumentParser()
ap.add_argument('file1', metavar='FILE1', type=file)
ap.add_argument('file2', metavar='FILE2', type=file)
options = ap.parse_args()

f1 = options.file1
f2 = options.file2

for i, l1, l2 in izip(count(1), chain(f1, repeat(None)), chain(f2, repeat(None))):
    if l1 is None:
        if l2 is None:
            break
        else:
            write('%da%d\n' % (i, i))
    elif l2 is None:
        write('%dd%d\n' % (i, i))
    else:
        if l1 == l2:
            continue
        write('%dc%d\n' % (i, i))
    l1 is None or write('< %s' % l1)
    l2 is None or write('> %s' % l2)

# vim:ts=4 sts=4 sw=4 et
